import type { AppDocument, GuidanceCategoriesConfig, GuidanceCategory } from '../types';

const EMPTY_CONFIG: GuidanceCategoriesConfig = { categories: [] };

/**
 * Loads public/guidance_categories.json — a hand-maintained lookup table mapping named
 * guideline categories (e.g. "結核病指引") to the guidance_docs filenames that belong to
 * them. Unlike manifest.json, this isn't generated by the build script: categorization is a
 * curatorial decision, so the project owner edits this file directly.
 */
export async function loadCategories(): Promise<GuidanceCategoriesConfig> {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}guidance_categories.json`, { cache: 'no-store' });
    if (!res.ok) return EMPTY_CONFIG;
    const data = (await res.json()) as GuidanceCategoriesConfig;
    if (!data || !Array.isArray(data.categories)) return EMPTY_CONFIG;
    return data;
  } catch {
    return EMPTY_CONFIG;
  }
}

/** Files present in guidance_docs but not listed under any category in the config. */
export function findUncategorizedFiles(docs: AppDocument[], categories: GuidanceCategory[]): string[] {
  const categorized = new Set(categories.flatMap((c) => c.files || []));
  return docs.map((d) => d.name).filter((name) => !categorized.has(name));
}

export const UNCATEGORIZED_ID = '__uncategorized__';

/** Picks a sensible default category to select once categories/files finish loading —
 *  the first defined category, or the uncategorized group if there are no categories but
 *  some files exist anyway. Empty string means "nothing to select yet". */
export function defaultCategoryId(categories: GuidanceCategory[], uncategorizedFiles: string[]): string {
  if (categories.length > 0) return categories[0].id;
  if (uncategorizedFiles.length > 0) return UNCATEGORIZED_ID;
  return '';
}

/** Resolves a category selection (a category id, or the special uncategorized-group id) down
 *  to the concrete filenames it covers — used to scope vector search / Full-Text Mode to just
 *  that single guideline's documents. There is deliberately no "search everything" option:
 *  every question is scoped to exactly one category. Returns null if the id doesn't resolve
 *  to anything (e.g. no category selected yet) — callers should treat that as "no documents
 *  in scope" rather than silently falling back to searching everything. */
export function resolveCategoryFilter(
  categoryId: string,
  categories: GuidanceCategory[],
  uncategorizedFiles: string[]
): string[] | null {
  if (!categoryId) return null;
  if (categoryId === UNCATEGORIZED_ID) return uncategorizedFiles;
  const category = categories.find((c) => c.id === categoryId);
  return category ? (category.files || []) : null;
}
