import type { AppDocument, GuidanceCategoriesConfig, GuidanceCategory } from '../types';

const EMPTY_CONFIG: GuidanceCategoriesConfig = { categories: [] };

/**
 * Loads public/guidance_categories.json — a hand-maintained lookup table mapping named
 * guideline categories (e.g. "結核病指引") to the guidance_docs filenames that belong to
 * them. Unlike manifest.json, this isn't generated by the build script: categorization is a
 * curatorial decision, so the project owner edits this file directly.
 */
export async function loadCategories(): Promise<GuidanceCategoriesConfig> {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}guidance_categories.json`, { cache: 'no-store' });
    if (!res.ok) return EMPTY_CONFIG;
    const data = (await res.json()) as GuidanceCategoriesConfig;
    if (!data || !Array.isArray(data.categories)) return EMPTY_CONFIG;
    return data;
  } catch {
    return EMPTY_CONFIG;
  }
}

/** Files present in guidance_docs but not listed under any category in the config. */
export function findUncategorizedFiles(docs: AppDocument[], categories: GuidanceCategory[]): string[] {
  const categorized = new Set(categories.flatMap((c) => c.files));
  return docs.map((d) => d.name).filter((name) => !categorized.has(name));
}

/** Resolves a category selection ('all' or a category id) down to the concrete filenames it
 *  covers — used to scope vector search / Full-Text Mode to just that guideline's documents.
 *  Returns null for 'all' (meaning: no filter, search everything). */
export function resolveCategoryFilter(
  categoryId: string | 'all',
  categories: GuidanceCategory[],
  uncategorizedFiles: string[]
): string[] | null {
  if (categoryId === 'all') return null;
  if (categoryId === '__uncategorized__') return uncategorizedFiles;
  const category = categories.find((c) => c.id === categoryId);
  return category ? category.files : null;
}
